InterviewWebsite/InterviewWebsite/InterviewWebsite/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('blog/', include('blog.urls')),
    path('admin/', admin.site.urls),
]

InterviewWebsite/InterviewWebsite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name='index'),
    path('home', views.home, name='home'),
    path('article/<slug:uuid>', views.article, name='article'),
    path('comment/<slug:uuid>', views.new_comment, name='comment'),
]

InterviewWebsite/InterviewWebsite/blog/models.py
import datetime
from django.db import models
from django.utils import timezone


class Author(models.Model):
    author_id = models.CharField(max_length=32)
    small_avatar_url = models.TextField()
    username = models.CharField(max_length=32)


class Comment(models.Model):
    comment_text = models.TextField(max_length=400)
    article_id = models.CharField(max_length=36)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published')

    def is_recent_comment(self, num_days=0):
        now = timezone.now()
        return now - datetime.timedelta(days=num_days) <= self.pub_date <= now

InterviewWebsite/InterviewWebsite/blog/views.py
import json, os, random

from datetime import datetime
from django.shortcuts import render
from .models import Comment, Author
from django.shortcuts import redirect


def get_content_json():
    with open(os.path.join(os.path.dirname(__file__), 'testData/content_api.json'), 'r', encoding='latin') as f:
        content_json = json.load(f)
    return content_json


def get_quote_json():
    with open(os.path.join(os.path.dirname(__file__), 'testData/quotes_api.json'), 'r', encoding='latin') as f:
        content_json = json.load(f)
    return content_json


def get_inst_details(instruments, quote_json):
    for inst in quote_json:
        if inst["InstrumentId"] in instruments.keys():
            instruments[inst["InstrumentId"]]["name"] = inst["CompanyName"]
            instruments[inst["InstrumentId"]]["exchange"] = inst["Exchange"]
            instruments[inst["InstrumentId"]]["ticker"] = inst["Symbol"]
            instruments[inst["InstrumentId"]]["last"] = inst["CurrentPrice"]["Amount"]
            instruments[inst["InstrumentId"]]["change"] = inst["Change"]["Amount"]
            instruments[inst["InstrumentId"]]["change_percent"] = inst["PercentChange"]["Value"]
    return instruments


def parse_json_base(json_data):
    data = {}
    data["headline"] = json_data["headline"]
    data["byline"] = json_data["byline"]
    data["promo"] = json_data["promo"]
    data["created"] = datetime.strptime(json_data["created"], '%Y-%m-%dT%H:%M:%SZ')
    data["modified"] = datetime.strptime(json_data["modified"], '%Y-%m-%dT%H:%M:%SZ')
    data["uuid"] = json_data["uuid"]
    for image in json_data["images"]:
        if image["featured"]:
            data["image"] = image["url"]
            break
    return data

def parse_json_details(json_data):
    data = parse_json_base(json_data)
    data["promo"] = json_data["promo"]
    data["body"] = json_data["body"].replace('Â', '').replace('{%sfr%}', '')
    data["disclosure"] = json_data["disclosure"]
    data["pitch"] = json_data["pitch"]["text"]
    for author in json_data["authors"]:
        if author["byline"] == data["byline"]:
            data["username"] = author["username"]
            break
    return data


def home(request):
    json_load = get_content_json()
    results = json_load["results"]
    find = False
    for result in results:
        for tag in result["tags"]:
            if "10-promise" == tag["slug"]:
                first = parse_json_base(result)
                find = True
                break
        if find:
            results.remove(result)
            break
    rest_results = random.sample(results, 3)
    rest = []
    for result in rest_results:
        rest.append(parse_json_base(result))
    return render(request, 'blog/home.html', {'first': first, 'rest': rest})


def load_date_for_article(uuid):
    content_json = get_content_json()
    results = content_json["results"]
    content = ''
    cur_result = ''
    for result in results:
        if uuid == result["uuid"]:
            cur_result = result
            content = parse_json_details(result)
            break
    quote_json = get_quote_json()
    instruments = {}
    for instrument in cur_result["instruments"]:
        instruments[instrument["instrument_id"]] = {}
    instruments = get_inst_details(instruments, quote_json)
    comments = Comment.objects.values('comment_text', 'pub_date', 'author_id__username', 'author_id__small_avatar_url').filter(article_id=uuid).order_by('-pub_date')[:5]
    author = Author.objects.get(author_id=1)
    data = {
        "content": content,
        "instruments": instruments,
        "comments": comments,
        "author": author
    }
    return data


def article(request, uuid):
    data = load_date_for_article(uuid)
    return render(request, 'blog/article.html', {'article': data["content"], 'insts': data["instruments"].values(), 'comments': data["comments"], 'author': data["author"]})


def new_comment(request, uuid):
    try:
        author = Author.objects.get(author_id=1)
        comment = Comment(comment_text=request.POST['comment'], article_id=uuid, pub_date=datetime.now(), author=author)
        comment.save()
    except:
        data = load_date_for_article(uuid)
        return render(request, 'blog/article.html', {'article': data["content"], 'insts': data["instruments"].values(), 'comments': data["comments"], 'error': "Comment is not valid.", })
    return redirect('../article/' + uuid + "#show_comments")

InterviewWebsite/InterviewWebsite/blog/templates/blog/article.html
{% extends "blog\base.html" %}
{% load static %}
{% block title %}{{ article.headline }}{% endblock %}
{% block custom_stylesheets %}
    {{ block.super }}
    <script src="{% static 'blog/scripts/main.js' %}"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'blog/comments.css' %}">
{% endblock %}

{% block content %}
<div class="container top-bar article-top-bar">
    <a href="{% url 'blog:home' %}" class="btn btn-primary">HOME</a>
</div>
<div class="container article-content-inner">
    <div class="row">
        <div class="col-sm-12">
            <div class="article-header">
                <header>
                    <div id="adv_text" class="adv-heading"></div>
                    <h1>{{ article.headline }}</h1>
                    <h2>{{ article.promo }}</h2>
                </header>
            </div>
        </div>
    </div>
    <div class="row">
        <main class="col-sm-7 col-md-8">
            <div class="author-tagline author-inline">
                <div class="author-and-date">
                    <div class="author-byline">
                        <div class="author-name">{{ article.byline }}</div>
                        <div class="author-username">
                            (<a href="#">{{ article.username }}</a>)
                        </div>
                    </div>
                    <div class="article-pub-date">
                        <div class="publication-date">
                            {{ article.created|date:"F d, Y" }} at {{ article.created|date:"h:iA" }}
                        </div>
                    </div>
                </div>
            </div>
            <section class="article-body">
                <div class="article-content">
                    {{ article.body|safe }}
                </div>
                <div class="article-disclosure">
                    {{ article.disclosure|safe }}
                </div>
                <div class="special-message">
                    {{ article.pitch|safe }}
                </div>
                <div class="comments">
                    {% include "blog/comments.html" %}
                </div>
            </section>
        </main>
        <aside class="col-sm-5 col-md-4 p-l">
            {% include "blog/tickers.html" %}
            {% include "blog/readmore.html" %}
        </aside>
    </div>
</div>
{% endblock %}

InterviewWebsite/InterviewWebsite/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
        <title>{% block title %}My amazing site{% endblock %}</title>
        <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet">
        <link rel="icon" type="image/png" href="{% static 'blog/images/fool.jpg' %}">

        <link rel="stylesheet" type="text/css" href="{% static 'blog/font-awesome.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'blog/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}">
        {% block custom_stylesheets %}{% endblock %}
    </head>
<body>
    {% block content %}{% endblock %}
    <script src="{% static 'blog/scripts/jquery-3.1.1.min.js' %}"></script>
    <script src="{% static 'blog/scripts/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/scripts/main.js' %}"></script>
</body>
</html>

InterviewWebsite/InterviewWebsite/blog/templates/blog/comments.html
{% if error %}<p><strong><span class="error">{{ error }}</span></strong></p>{% endif %}
<form action="{% url 'blog:comment' article.uuid %}" method="post">
    {% csrf_token %}
    <label for="comment_area">{{ author.username }}, have your say in 400 chars or less</label><br>
    <textarea name="comment" id="comment_area" ></textarea><br>
    <input type="submit" value="submit">
</form>
<div id="show_comments" class="past-comments">
{% if comments %}
    {% for comment in comments %}
    <div class="posted-comment clearfix">
        <span class="comments-avatar">
            <img src="{{ comment.author_id__small_avatar_url }}"></img>
        </span>
        <span class="comments-text">
            <p class="comments-header"><strong>{{ comment.author_id__username }}</strong> - {{ comment.pub_date }}</p>
            <p class="comments-content">{{ comment.comment_text }}</p>
        </span>
    </div>
    {% endfor %}
{% endif %}
</div>

InterviewWebsite/InterviewWebsite/blog/templates/blog/home.html
{% extends "blog\base.html" %}
{% load static %}
{% block title %}Interview Website{% endblock %}

{% block content %}
<div class="content">
    <div class="container top-bar">
        <a href="{% url 'blog:home' %}" class="btn btn-primary">HOME</a>
    </div>
    <div class="container content-inner">
        <div class="main-col">
            <section class="jumbo-card card">
                <div class="card-image">
                    <a href="{% url 'blog:article' first.uuid %}"><img src="{{ first.image }}" alt="" class="img-responsive"></a>
                </div>
                <div class="card-elements">
                    <div class="card-header">
                        <a href="{% url 'blog:article' first.uuid %}"><h3>{{ first.headline }}</h3></a>
                        <p class="author">{{ first.byline }} | {{ first.created|date:"F d, Y" }}</p>
                    </div>
                    <div class="card-copy">
                        <p>{{ first.promo }}</p>
                    </div>
                </div>
            </section>
        </div>
        <div class="cards row">
        {% for headline in rest %}
            <div class="card">
                <div class="card-image">
                    <a href="{% url 'blog:article' headline.uuid %}">
                        <img src="{{ headline.image }}" alt="">
                    </a>
                </div>
                <div class="card-elements">
                    <div class="card-header">
                        <a href="{% url 'blog:article' headline.uuid %}">
                            <h4>{{ headline.headline }}</h4>
                        </a>
                        <p class="author">{{ headline.byline }} | {{ headline.created|date:"F d, Y" }}</p>
                    </div>
                    <div class="card-copy">
                        <p>{{ headline.promo }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

InterviewWebsite/InterviewWebsite/blog/templates/blog/readmore.html
{% load static %}

<section class="read-more-section">
    <div class="block-title">
        <hr><h2>Read More</h2>
    </div>
    <ul class="two-line-list">
        <li><a href="#">It is a long established fact that a reader</a></li>
        <li><a href="#">Many desktop publishing packages and web page editors now use</a></li>
        <li><a href="#">Contrary to popular belief, Lorem Ipsum is not simply random text</a></li>
        <li><a href="#">There are many variations of passa</a></li>
        <li><a href="#" >If you are going to use a passage of Lorem Ipsum</a></li>
    </ul>
</section>

InterviewWebsite/InterviewWebsite/blog/templates/blog/tickers.html
<section class="related-tickers">
    <div class="block-title">
        <hr><h2>Stocks</h2>
    </div>
    <div id="ticker-list">
    {% for inst in insts %}
        <div class="ticker-row clearfix">
            <div>
                <span class="image-wrap">
                    <a href="#">
                        {{ inst.ticker }}
                    </a>
                </span>
                <h3>{{ inst.name }}</h3>
                <h4>
                    <span class="ticker">
                        <a title="{{ inst.name }} Stock Quote" href="#">
                            {{ inst.exchange }}:<span class="symbol">{{ inst.ticker }}</span>
                        </a>
                    </span>
                </h4>
                <aside class="price-quote-container">
                    <h4 class="current-price">
                        ${{ inst.last }}
                    </h4>
                    <h4 class="price-change-amount {% if inst.change > 0 %} price-pos {% else %} price-neg {% endif %}">
                        ${{ inst.change|floatformat:2 }}
                    </h4>
                    <h4 class="price-change-percent {% if inst.change_percent > 0 %} price-pos {% else %} price-neg {% endif %}">
                        ({{ inst.change_percent|floatformat:2 }}%)
                    </h4>
                </aside>
            </div>
        </div>
    {% endfor %}
    </div>
    <button onclick="shuffle('ticker-list')">Shuffle Stocks</button>
</section>